### ISSUE TITLE
SD library issues

### ISSUE THREAD

**Issue by fpistm** [stm32duino/STM32SD#1]
_From @fpistm on May 18, 2017 15:46_

Link to SD lib need some correction.

_Copied from original issue: stm32duino/Arduino_Core_STM32#2_

**Comment by fpistm** [comment]
Update/correct the modified SD library. In case of TFT bitmap logo example, File object is passed as an argument to R/W function but like File object is copied the current file pointer is reset so it is always read from the beginning.

**Comment by ppescher** [comment]
Hi @fpistm 

I was using this library together with STM32FreeRTOS and I was concerned by library code that makes use of `malloc()`, such as this or even `String` from Arduino core.

I solved it by providing some hook functions for newlib to handle mutual exclusion and reentrancy problems ( I can prepare a PR for that if you want), but I was wondering if dynamic memory allocation was actually necessary here.

What exactly was the issue with the previous version, with a member FIL structure? Can't we just provide a copy constructor? Or pass File objects by reference/pointer instead of by value?

**Comment by fpistm** [comment]
The issue was in some case the SDFile is passed to function which do some read.
In this case, the FIL member was simply copied so when returning the fp was not at the good position.

Example here:
https://github.com/arduino-libraries/TFT/blob/d52cb5d334dbbc0f3931c924106b0d5c8aba6ba7/src/utility/Adafruit_GFX.h#L327

bmpfile is used several time and so always read from the beginning as the Fil was not dynamic.

About the PR I'm always interested by improvement. Thanks in advance.
